import { useAppStore } from '@/store/appSchema'

// Wails v2 Go bindings - these are auto-generated by Wails
// For now, typed as any since the bindings are generated at build time
declare const window: any

function getGoBinding() {
  return window['go']?.['main']?.['App']
}

// Helper to get current userId from store
function getCurrentUserId(): string {
  const store = useAppStore()
  return store?.getCurrentUserInfo?.userId || 'user1'
}

// Helper to convert Wails Result to HTTP-compatible response
function unwrapResult(result: any) {
  if (result && typeof result === 'object' && 'code' in result) {
    return result
  }
  return result
}

// ---- Image ----

// 路径方案：打开原生文件选择框，立即返回文件路径列表，后台分批解析并推送事件
export async function selectImages() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SelectImages()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 监听一批图片解析完成
export function onImagesParsed(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-parsed', callback)
}

// 监听解析进度
export function onImagesProgress(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-progress', callback)
}

// 监听全部解析完成
export function onImagesDone(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-done', callback)
}

// 清理所有图片解析事件监听（组件卸载时调用，防止内存泄漏）
export function offImagesEvents() {
  window.runtime?.EventsOff?.('images-parsed')
  window.runtime?.EventsOff?.('images-progress')
  window.runtime?.EventsOff?.('images-done')
}

// 路径方案：将选中的图片文件导入到用户目录
export async function importImages(data: { images: any[] }) {
  const binding = getGoBinding()
  if (binding) {
    const files = (data.images || []).map((img: any) => ({
      id: img.id,
      name: img.name,
      path: img.path,
    }))
    const result = await binding.ImportImages(getCurrentUserId(), files)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function uploadImages(data: any) {
  const binding = getGoBinding()
  if (binding) {
    const rawImages = data.images || data
    const images = rawImages.map((img: any) => ({
      id: img.id,
      name: img.name,
      url: img.url || '',
      thumbnailUrl: img.thumbnailUrl || '',
    }))
    const result = await binding.UploadImages(getCurrentUserId(), images)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetThumbnail(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getImages(data: { imageIds: string[] }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetThumbnails(getCurrentUserId(), data.imageIds)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteImages(data: { deleteImages: string[] }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteImages(getCurrentUserId(), data.deleteImages)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function updateImages(data: any) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.UpdateImages()
    return unwrapResult(result)
  }
  return { code: 200, msg: '成功', data: null, time: Date.now() }
}

export async function downloadImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DownloadImage(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getJPGImage(file: File): Promise<{ code: number; msg: string; data: Blob }> {
  // For Wails, convert File to base64 then call convert on Go side
  const binding = getGoBinding()
  if (binding) {
    const buffer = await file.arrayBuffer()
    const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)))
    const result = await binding.ConvertImage(base64, file.name)
    if (result.code === 200 && result.data) {
      const byteString = atob(result.data.file || result.data)
      const bytes = new Uint8Array(byteString.length)
      for (let i = 0; i < byteString.length; i++) {
        bytes[i] = byteString.charCodeAt(i)
      }
      return { code: 200, msg: '成功', data: new Blob([bytes], { type: 'image/jpeg' }) }
    }
    return { code: result.code, msg: result.msg, data: new Blob() }
  }
  throw new Error('Wails bindings not available')
}

// ---- Schema ----

export async function getSchema(params?: { currentUserId?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const userId = params?.currentUserId || getCurrentUserId()
    const result = await binding.GetSchema(userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function setSchema(data: { schema: string; currentUserId?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const userId = data.currentUserId || getCurrentUserId()
    const result = await binding.SetSchema(userId, data.schema)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- AppSchema ----

export async function getUserInfos(params?: any) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetUserInfos()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getAppSchema() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetAppSchema()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function setAppSchema(data: { schema: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SetAppSchema(data.schema)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Track ----

export async function uploadTrack(file: File) {
  const binding = getGoBinding()
  if (binding) {
    const buffer = await file.arrayBuffer()
    const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)))
    const result = await binding.UploadTrack(getCurrentUserId(), base64, file.name)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteTrack(fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteTrack(getCurrentUserId(), fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getTrack(fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetTrack(getCurrentUserId(), fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Backup ----

export async function createBackup(data: { name?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.CreateBackup(data.name || '')
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getBackupSize() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetBackupSize()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getBackupList() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetBackupList()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function importBackup(data: { filePath: string; mode: 'cover' | 'merge' }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.ImportBackup(data.filePath, data.mode)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteBackup(data: { filePath: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteBackup(data.filePath)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- User ----

export async function createUserDir(data: { userId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.CreateUser(data.userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteUserDir(data: { userId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteUser(data.userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 以模块对象导出，保持与原 HTTP API 相同的调用形态（API.image.xxx / API.schema.xxx）
const image = {
  selectImages,
  importImages,
  uploadImages,
  getImage,
  getImages,
  deleteImages,
  updateImages,
  downloadImage,
  getJPGImage,
  onImagesParsed,
  onImagesProgress,
  onImagesDone,
  offImagesEvents,
}

const schema = {
  getSchema,
  setSchema,
}

const appSchema = {
  getUserInfos,
  getAppSchema,
  setAppSchema,
}

const track = {
  uploadTrack,
  deleteTrack,
  getTrack,
}

const backup = {
  backup: createBackup,
  getBackupSize,
  getBackupList,
  import: importBackup,
  deleteBackup,
}

const user = {
  createUserDir,
  deleteUserDir,
}

// Default export matching original http/index.ts API shape
const API: Record<string, any> = {
  image,
  schema,
  appSchema,
  track,
  backup,
  user,
}

export default API
