import { useAppStore } from '@/store/appSchema'

// Wails v2 Go bindings - these are auto-generated by Wails
// For now, typed as any since the bindings are generated at build time
declare const window: any

function getGoBinding() {
  return window['go']?.['main']?.['App']
}

// Helper to get current userId from store
function getCurrentUserId(): string {
  const store = useAppStore()
  return store?.getCurrentUserInfo?.userId || 'user1'
}

// Helper to convert Wails Result to HTTP-compatible response
function unwrapResult(result: any) {
  if (result && typeof result === 'object' && 'code' in result) {
    return result
  }
  return result
}

// ---- Image ----

// 路径方案：打开原生文件选择框，立即返回文件路径列表，后台分批解析并推送事件
export async function selectImages() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SelectImages()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 监听一批图片解析完成
export function onImagesParsed(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-parsed', callback)
}

// 监听解析进度
export function onImagesProgress(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-progress', callback)
}

// 监听全部解析完成
export function onImagesDone(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('images-done', callback)
}

// 清理所有图片解析事件监听（组件卸载时调用，防止内存泄漏）
export function offImagesEvents() {
  window.runtime?.EventsOff?.('images-parsed')
  window.runtime?.EventsOff?.('images-progress')
  window.runtime?.EventsOff?.('images-done')
}

// 路径方案：将选中的图片文件导入到用户目录
export async function importImages(data: { images: any[] }) {
  const binding = getGoBinding()
  if (binding) {
    const files = (data.images || []).map((img: any) => ({
      id: img.id,
      name: img.name,
      path: img.path,
    }))
    const result = await binding.ImportImages(getCurrentUserId(), files)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetThumbnail(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// marker 专用小尺寸缩略图（120px），缩放加载时减少解码开销
export async function getMarkerImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetMarkerThumbnail(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteImages(data: { deleteImages: string[] }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteImages(getCurrentUserId(), data.deleteImages)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function updateImages(data: any) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.UpdateImages()
    return unwrapResult(result)
  }
  return { code: 200, msg: '成功', data: null, time: Date.now() }
}

export async function downloadImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DownloadImage(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 获取原图（完整分辨率 base64），用于全景预览
export async function getFullImage(data: { imageId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetFullImage(getCurrentUserId(), data.imageId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Schema ----

export async function getSchema(params?: { currentUserId?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const userId = params?.currentUserId || getCurrentUserId()
    const result = await binding.GetSchema(userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function setSchema(data: { schema: string; currentUserId?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const userId = data.currentUserId || getCurrentUserId()
    const result = await binding.SetSchema(userId, data.schema)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- AppSchema ----

export async function getUserInfos(params?: any) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetUserInfos()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getAppSchema() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetAppSchema()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function setAppSchema(data: { schema: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SetAppSchema(data.schema)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Track ----

export async function uploadTrack(file: File) {
  const binding = getGoBinding()
  if (binding) {
    const buffer = await file.arrayBuffer()
    const base64 = arrayBufferToBase64(buffer)
    const result = await binding.UploadTrack(getCurrentUserId(), base64, file.name)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 分块转 base64，避免大文件展开导致调用栈溢出
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer)
  const chunkSize = 0x8000
  let binary = ''
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize))
  }
  return btoa(binary)
}

export async function deleteTrack(fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteTrack(getCurrentUserId(), fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getTrack(fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetTrack(getCurrentUserId(), fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Video (轨迹视频) ----

export async function selectVideos() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SelectVideos()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function importVideo(data: { id: string; name: string; path: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.ImportVideo(getCurrentUserId(), data)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteVideos(data: { videoIds: string[] }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteVideos(getCurrentUserId(), data.videoIds)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getVideoRange(data: { videoId: string; start: number; end: number }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetVideoRange(getCurrentUserId(), data.videoId, data.start, data.end)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 视频第一帧封面（地图标记用），返回 { file: base64 }
export async function getVideoThumbnail(data: { videoId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetVideoThumbnail(getCurrentUserId(), data.videoId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 批量获取视频封面
export async function getVideoThumbnails(data: { videoIds: string[] }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetVideoThumbnails(getCurrentUserId(), data.videoIds)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 从任意路径提取视频第一帧封面（待上传视频预览），返回 { file: base64 }
export async function getVideoFramePreview(data: { path: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetVideoFramePreview(data.path)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 监听一批视频解析完成
export function onVideosParsed(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('videos-parsed', callback)
}

// 监听视频解析进度
export function onVideosProgress(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('videos-progress', callback)
}

// 监听全部视频解析完成
export function onVideosDone(callback: (data: any) => void) {
  window.runtime?.EventsOn?.('videos-done', callback)
}

// 清理所有视频解析事件监听
export function offVideosEvents() {
  window.runtime?.EventsOff?.('videos-parsed')
  window.runtime?.EventsOff?.('videos-progress')
  window.runtime?.EventsOff?.('videos-done')
}

// ---- Backup ----

export async function createBackup(data: { name?: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.CreateBackup(data.name || '')
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getBackupSize() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetBackupSize()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getBackupList() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetBackupList()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function importBackup(data: { filePath: string; mode: 'cover' | 'merge' }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.ImportBackup(data.filePath, data.mode)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteBackup(data: { filePath: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteBackup(data.filePath)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Icon (全局图标库) ----

export async function uploadIcon(fileName: string, file: File, category: string) {
  const binding = getGoBinding()
  if (binding) {
    const buffer = await file.arrayBuffer()
    const base64 = arrayBufferToBase64(buffer)
    const result = await binding.UploadIcon(fileName, base64, category)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function getIcon(category: string, fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetIcon(category, fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteIcon(category: string, fileName: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteIcon(category, fileName)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function listIcons(category: string) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.ListIcons(category)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- Storage (存储目录) ----

export async function getStorageConfig() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.GetStorageConfig()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function selectDirectory() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SelectDirectory()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function selectBackupFile() {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SelectBackupFile()
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function setStorageConfig(data: { archiveDir: string; backupDir: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.SetStorageConfig(data.archiveDir, data.backupDir)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// ---- User ----

export async function createUserDir(data: { userId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.CreateUser(data.userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

export async function deleteUserDir(data: { userId: string }) {
  const binding = getGoBinding()
  if (binding) {
    const result = await binding.DeleteUser(data.userId)
    return unwrapResult(result)
  }
  throw new Error('Wails bindings not available')
}

// 以模块对象导出，保持与原 HTTP API 相同的调用形态（API.image.xxx / API.schema.xxx）
const image = {
  selectImages,
  importImages,
  getImage,
  getMarkerImage,
  deleteImages,
  updateImages,
  downloadImage,
  getFullImage,
  onImagesParsed,
  onImagesProgress,
  onImagesDone,
  offImagesEvents,
}

const schema = {
  getSchema,
  setSchema,
}

const appSchema = {
  getUserInfos,
  getAppSchema,
  setAppSchema,
}

const track = {
  uploadTrack,
  deleteTrack,
  getTrack,
}

const video = {
  selectVideos,
  importVideo,
  deleteVideos,
  getVideoRange,
  getVideoThumbnail,
  getVideoThumbnails,
  getVideoFramePreview,
  onVideosParsed,
  onVideosProgress,
  onVideosDone,
  offVideosEvents,
}

const backup = {
  backup: createBackup,
  getBackupSize,
  getBackupList,
  import: importBackup,
  deleteBackup,
}

const user = {
  createUserDir,
  deleteUserDir,
}

const icon = {
  uploadIcon,
  getIcon,
  deleteIcon,
  listIcons,
}

const storage = {
  getStorageConfig,
  selectDirectory,
  selectBackupFile,
  setStorageConfig,
}

// Default export matching original http/index.ts API shape
const API: Record<string, any> = {
  image,
  schema,
  appSchema,
  track,
  video,
  backup,
  user,
  icon,
  storage,
}

export default API
