// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteIcon(arg1, arg2) {
  return window['go']['main']['App']['DeleteIcon'](arg1, arg2);
}

export function DeleteImages(arg1, arg2) {
  return window['go']['main']['App']['DeleteImages'](arg1, arg2);
}

export function DeleteTrack(arg1, arg2) {
  return window['go']['main']['App']['DeleteTrack'](arg1, arg2);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeleteVideos(arg1, arg2) {
  return window['go']['main']['App']['DeleteVideos'](arg1, arg2);
}

export function DownloadImage(arg1, arg2) {
  return window['go']['main']['App']['DownloadImage'](arg1, arg2);
}

export function GetAppSchema() {
  return window['go']['main']['App']['GetAppSchema']();
}

export function GetBackupList() {
  return window['go']['main']['App']['GetBackupList']();
}

export function GetBackupSize() {
  return window['go']['main']['App']['GetBackupSize']();
}

export function GetFullImage(arg1, arg2) {
  return window['go']['main']['App']['GetFullImage'](arg1, arg2);
}

export function GetIcon(arg1, arg2) {
  return window['go']['main']['App']['GetIcon'](arg1, arg2);
}

export function GetMarkerThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetMarkerThumbnail'](arg1, arg2);
}

export function GetSchema(arg1) {
  return window['go']['main']['App']['GetSchema'](arg1);
}

export function GetStorageConfig() {
  return window['go']['main']['App']['GetStorageConfig']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetThumbnails(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnails'](arg1, arg2);
}

export function GetTrack(arg1, arg2) {
  return window['go']['main']['App']['GetTrack'](arg1, arg2);
}

export function GetUserInfos() {
  return window['go']['main']['App']['GetUserInfos']();
}

export function GetVideoFramePreview(arg1) {
  return window['go']['main']['App']['GetVideoFramePreview'](arg1);
}

export function GetVideoRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVideoRange'](arg1, arg2, arg3, arg4);
}

export function GetVideoThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetVideoThumbnail'](arg1, arg2);
}

export function GetVideoThumbnails(arg1, arg2) {
  return window['go']['main']['App']['GetVideoThumbnails'](arg1, arg2);
}

export function ImportBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2);
}

export function ImportImages(arg1, arg2) {
  return window['go']['main']['App']['ImportImages'](arg1, arg2);
}

export function ImportVideo(arg1, arg2) {
  return window['go']['main']['App']['ImportVideo'](arg1, arg2);
}

export function ListIcons(arg1) {
  return window['go']['main']['App']['ListIcons'](arg1);
}

export function SelectBackupFile() {
  return window['go']['main']['App']['SelectBackupFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SelectVideos() {
  return window['go']['main']['App']['SelectVideos']();
}

export function SetAppSchema(arg1) {
  return window['go']['main']['App']['SetAppSchema'](arg1);
}

export function SetSchema(arg1, arg2) {
  return window['go']['main']['App']['SetSchema'](arg1, arg2);
}

export function SetStorageConfig(arg1, arg2) {
  return window['go']['main']['App']['SetStorageConfig'](arg1, arg2);
}

export function UpdateImages() {
  return window['go']['main']['App']['UpdateImages']();
}

export function UploadIcon(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadIcon'](arg1, arg2, arg3);
}

export function UploadTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadTrack'](arg1, arg2, arg3);
}
