// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateBackup(arg1:string):Promise<model.Result>;

export function CreateUser(arg1:string):Promise<model.Result>;

export function DeleteBackup(arg1:string):Promise<model.Result>;

export function DeleteIcon(arg1:string,arg2:string):Promise<model.Result>;

export function DeleteImages(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function DeleteTrack(arg1:string,arg2:string):Promise<model.Result>;

export function DeleteUser(arg1:string):Promise<model.Result>;

export function DeleteVideos(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function DownloadImage(arg1:string,arg2:string):Promise<model.Result>;

export function GetAppSchema():Promise<model.Result>;

export function GetBackupList():Promise<model.Result>;

export function GetBackupSize():Promise<model.Result>;

export function GetFullImage(arg1:string,arg2:string):Promise<model.Result>;

export function GetIcon(arg1:string,arg2:string):Promise<model.Result>;

export function GetMarkerThumbnail(arg1:string,arg2:string):Promise<model.Result>;

export function GetSchema(arg1:string):Promise<model.Result>;

export function GetStorageConfig():Promise<model.Result>;

export function GetThumbnail(arg1:string,arg2:string):Promise<model.Result>;

export function GetThumbnails(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function GetTrack(arg1:string,arg2:string):Promise<model.Result>;

export function GetUserInfos():Promise<model.Result>;

export function GetVideoFramePreview(arg1:string):Promise<model.Result>;

export function GetVideoRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<model.Result>;

export function GetVideoStreamUrl(arg1:string,arg2:string):Promise<model.Result>;

export function GetVideoThumbnail(arg1:string,arg2:string):Promise<model.Result>;

export function GetVideoThumbnails(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function ImportBackup(arg1:string,arg2:string):Promise<model.Result>;

export function ImportImages(arg1:string,arg2:Array<model.ImportFile>):Promise<model.Result>;

export function ImportVideo(arg1:string,arg2:model.ImportVideoFile):Promise<model.Result>;

export function ListIcons(arg1:string):Promise<model.Result>;

export function SelectBackupFile():Promise<model.Result>;

export function SelectDirectory():Promise<model.Result>;

export function SelectImages():Promise<model.Result>;

export function SelectVideos():Promise<model.Result>;

export function SetAppSchema(arg1:string):Promise<model.Result>;

export function SetSchema(arg1:string,arg2:string):Promise<model.Result>;

export function SetStorageConfig(arg1:string,arg2:string):Promise<model.Result>;

export function UpdateImages():Promise<model.Result>;

export function UploadIcon(arg1:string,arg2:string,arg3:string):Promise<model.Result>;

export function UploadTrack(arg1:string,arg2:string,arg3:string):Promise<model.Result>;
