// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteImages(arg1, arg2) {
  return window['go']['main']['App']['DeleteImages'](arg1, arg2);
}

export function DeleteTrack(arg1, arg2) {
  return window['go']['main']['App']['DeleteTrack'](arg1, arg2);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadImage(arg1, arg2) {
  return window['go']['main']['App']['DownloadImage'](arg1, arg2);
}

export function GetAppSchema() {
  return window['go']['main']['App']['GetAppSchema']();
}

export function GetBackupList() {
  return window['go']['main']['App']['GetBackupList']();
}

export function GetBackupSize() {
  return window['go']['main']['App']['GetBackupSize']();
}

export function GetFullImage(arg1, arg2) {
  return window['go']['main']['App']['GetFullImage'](arg1, arg2);
}

export function GetSchema(arg1) {
  return window['go']['main']['App']['GetSchema'](arg1);
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetThumbnails(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnails'](arg1, arg2);
}

export function GetTrack(arg1, arg2) {
  return window['go']['main']['App']['GetTrack'](arg1, arg2);
}

export function GetUserInfos() {
  return window['go']['main']['App']['GetUserInfos']();
}

export function ImportBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2);
}

export function ImportImages(arg1, arg2) {
  return window['go']['main']['App']['ImportImages'](arg1, arg2);
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SetAppSchema(arg1) {
  return window['go']['main']['App']['SetAppSchema'](arg1);
}

export function SetSchema(arg1, arg2) {
  return window['go']['main']['App']['SetSchema'](arg1, arg2);
}

export function UpdateImages() {
  return window['go']['main']['App']['UpdateImages']();
}

export function UploadTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadTrack'](arg1, arg2, arg3);
}
