// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateBackup(arg1:string):Promise<model.Result>;

export function CreateUser(arg1:string):Promise<model.Result>;

export function DeleteBackup(arg1:string):Promise<model.Result>;

export function DeleteImages(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function DeleteTrack(arg1:string,arg2:string):Promise<model.Result>;

export function DeleteUser(arg1:string):Promise<model.Result>;

export function DownloadImage(arg1:string,arg2:string):Promise<model.Result>;

export function GetAppSchema():Promise<model.Result>;

export function GetBackupList():Promise<model.Result>;

export function GetBackupSize():Promise<model.Result>;

export function GetFullImage(arg1:string,arg2:string):Promise<model.Result>;

export function GetSchema(arg1:string):Promise<model.Result>;

export function GetThumbnail(arg1:string,arg2:string):Promise<model.Result>;

export function GetThumbnails(arg1:string,arg2:Array<string>):Promise<model.Result>;

export function GetTrack(arg1:string,arg2:string):Promise<model.Result>;

export function GetUserInfos():Promise<model.Result>;

export function ImportBackup(arg1:string,arg2:string):Promise<model.Result>;

export function SetAppSchema(arg1:string):Promise<model.Result>;

export function SetSchema(arg1:string,arg2:string):Promise<model.Result>;

export function UpdateImages():Promise<model.Result>;

export function UploadImages(arg1:string,arg2:Array<model.UploadImage>):Promise<model.Result>;

export function UploadTrack(arg1:string,arg2:string,arg3:string):Promise<model.Result>;
